name: bmad-film-pre-production
version: 1.0.0
short-title: Film Pre-Production Pack
description: An expansion pack for the BMad Method specialized for film pre-production.
author: Jules
slashPrefix: bmadfilm
